### ISSUE TITLE
请问支持在手机或者平板上触摸拖拽组件吗？

### ISSUE THREAD

**Issue by TangStudio** [hcg1023/vue3-dnd#17]
如题，感谢

**Comment by hcg1023** [comment]
当然支持，可以使用[react-dnd-touch-backend](https://www.npmjs.com/package/react-dnd-touch-backend)来实现移动端支持
参考文档：[https://hcg1023.github.io/vue3-dnd/guide/backend/touch.html](https://hcg1023.github.io/vue3-dnd/guide/backend/touch.html)
