### ISSUE TITLE
vue 3.0 项目中使用报错

### ISSUE THREAD

**Issue by liyangyangi** [hcg1023/vue3-dnd#18]
![83f80e99f652f37f81971dda6fe4c08](https://user-images.githubusercontent.com/22519600/172323606-cd97a6fa-0da8-40e1-815a-6e07dcbfff4d.png)

**Comment by hcg1023** [comment]
@liyangyangi 是不是没有包 DndProvider [https://hcg1023.github.io/vue3-dnd/guide/components/dnd-provider.html](https://hcg1023.github.io/vue3-dnd/guide/components/dnd-provider.html)
