### ISSUE TITLE
ts 提示类型错误

### ISSUE THREAD

**Issue by Aiamjay** [hcg1023/vue3-dnd#19]
<img width="836" alt="Screen Shot 2022-06-16 at 9 33 31 PM" src="https://user-images.githubusercontent.com/13723721/174225584-f6d774a5-2798-4e43-b877-45c1cf90c478.png">

**Comment by Aiamjay** [comment]
请问大佬如何解决这个错误提示？

**Comment by hcg1023** [comment]
> 请问大佬如何解决这个错误提示？

vue3？vue3-dnd的版本是多少？给个简单的代码看一下

**Comment by hcg1023** [comment]
vue2的话，参考https://hcg1023.github.io/vue3-dnd/guide/vue2.html

**Comment by Aiamjay** [comment]
`
<template>
  <div :ref="drag" role="Node" class="box" :class="{ ghost: isDragging }">
    <TreeRoot />
  </div>
</template>

<script lang="ts" setup>
import { useDrag } from 'vue3-dnd'
import { toRefs } from '@vueuse/core'
import TreeRoot from '../nodes/TreeRoot.vue'

const props = defineProps<{ name: string; type: String }>()

const [collect, drag] = useDrag(() => ({
  type: 'box',
  item: () => props,
  collect: (monitor) => ({
    isDragging: monitor.isDragging(),
    handlerId: monitor.getHandlerId(),
  }),
}))

const { isDragging } = toRefs(collect)
</script>

<style lang="scss" scoped>
.box {
  cursor: move;
  width: 150px;
  height: 100px;
  box-shadow: none;

  &.dragging {
    opacity: 0.4;
  }

  &.ghost {
    opacity: 0.4;
  }
}
</style>

`

**Comment by Aiamjay** [comment]
```
<template>
  <div :ref="drag" role="Node" class="box" :class="{ ghost: isDragging }">
    <TreeRoot />
  </div>
</template>

<script lang="ts" setup>
import { useDrag } from 'vue3-dnd'
import { toRefs } from '@vueuse/core'
import TreeRoot from '../nodes/TreeRoot.vue'

const props = defineProps<{ name: string; type: String }>()

const [collect, drag] = useDrag(() => ({
  type: 'box',
  item: () => props,
  collect: (monitor) => ({
    isDragging: monitor.isDragging(),
    handlerId: monitor.getHandlerId(),
  }),
}))

const { isDragging } = toRefs(collect)
</script>

<style lang="scss" scoped>
.box {
  cursor: move;
  width: 150px;
  height: 100px;
  box-shadow: none;

  &.dragging {
    opacity: 0.4;
  }

  &.ghost {
    opacity: 0.4;
  }
}
</style>

```

**Comment by Aiamjay** [comment]
功能正常，就是这个地方 vscode typescript 会提出 给 template ref 的 变量，类型不对

**Comment by hcg1023** [comment]
那我觉得可能是vscode类型那不太对，是volar插件吗？还是vetur？

**Comment by Aiamjay** [comment]
volar

**Comment by hcg1023** [comment]
可能是类型定义这块儿有些问题，今晚会修一下

**Comment by hcg1023** [comment]
原因是vue3的ref函数类型是`(ref: Element | ComponentPublicInstance | null, refs: Record<string, any>) => void`，但是我们的connect函数不接收`ComponentPublicInstance`类型的内容，不影响功能

**Comment by hcg1023** [comment]
仔细研究了一下，这个是在vue@3.2.25以后引起的问题，具体的原因不太清楚，已经在vue发起了一个讨论https://github.com/vuejs/core/discussions/6132

**Comment by hcg1023** [comment]
@Aiamjay 这个问题还存在吗？已修复的话就关闭issue了
