### ISSUE TITLE
拖拽源使用element-plus的table组件，导致拖拽源的拖拽预览dom高度超出如何解决？

### ISSUE THREAD

**Issue by liuuky** [hcg1023/vue3-dnd#23]
## table的body内容可滑动
![IMG101](https://user-images.githubusercontent.com/28673557/176336054-10be5d57-599b-4979-a20b-3b20ba21aaf9.png)

## 超出dom高度依赖于table的body内容的高度
![IMG103](https://user-images.githubusercontent.com/28673557/176336393-8dfe4b5d-dda6-42b8-b254-cd20d7172637.png)

## 拖拽其他元素对比
![IMG102](https://user-images.githubusercontent.com/28673557/176336080-02a8f666-ae4e-4767-9d00-84f42ce76606.png)

**Comment by hcg1023** [comment]
可以提供一个复现的链接吗？git仓库就可以

**Comment by liuuky** [comment]
仓库地址：https://github.com/liuuky/vue3-dnd-test

> git仓库就可以提供一个复现的链接吗？

**Comment by hcg1023** [comment]
@liuuky 我测试了react-dnd，它也存在同样的问题，问题主要出现在chrome浏览器，safari没有发现同样的问题，目前已经提交给了react-dnd，https://github.com/react-dnd/react-dnd/issues/3471

**Comment by hcg1023** [comment]
@liuuky 我觉得我找到了解决方案
可以给drag元素添加`transform: translateZ(0);`或者`transform: translate3d(0, 0, 0);`就可以解决这个问题
https://github.com/react-dnd/react-dnd/issues/832
https://github.com/react-dnd/react-dnd/issues/1608

**Comment by liuuky** [comment]
> @liuuky 我觉得我找到了解决方案 可以给drag元素添加`transform: translateZ(0);`或者`transform: translate3d(0, 0, 0);`就可以解决这个问题 [react-dnd/react-dnd#832](https://github.com/react-dnd/react-dnd/issues/832) [react-dnd/react-dnd#1608](https://github.com/react-dnd/react-dnd/issues/1608)

这个方法可以解决，感谢您的回复和帮助！

**Comment by hcg1023** [comment]
> > @liuuky 我觉得我找到了解决方案 可以给drag元素添加`transform: translateZ(0);`或者`transform: translate3d(0, 0, 0);`就可以解决这个问题 [react-dnd/react-dnd#832](https://github.com/react-dnd/react-dnd/issues/832) [react-dnd/react-dnd#1608](https://github.com/react-dnd/react-dnd/issues/1608)
> 
> 这个方法可以解决，感谢您的回复和帮助！

没关系，有帮助的话可以点个star

**Comment by liuuky** [comment]
> > > @liuuky 我觉得我找到了解决方案 可以给drag元素添加`transform: translateZ(0);`或者`transform: translate3d(0, 0, 0);`就可以解决这个问题 [react-dnd/react-dnd#832](https://github.com/react-dnd/react-dnd/issues/832) [react-dnd/react-dnd#1608](https://github.com/react-dnd/react-dnd/issues/1608)
> > 
> > 
> > 这个方法可以解决，感谢您的回复和帮助！
> 
> 没关系，有帮助的话可以点个star

👌🏻用的时候已star过

**Comment by hcg1023** [comment]
> 👌🏻用的时候已star过

感谢
