### ISSUE TITLE
请问可以改变拖拽时鼠标样式吗？比如cursor: grabbing

### ISSUE THREAD

**Issue by fanties** [hcg1023/vue3-dnd#26]
请问可以改变拖拽时鼠标样式吗？比如cursor: grabbing

**Comment by hcg1023** [comment]
直接修改css样式就可以
<img width="931" alt="image" src="https://user-images.githubusercontent.com/47942469/180588936-1ebd25e8-753e-45f2-a113-3a231d9354cc.png">

**Comment by hcg1023** [comment]
https://github.com/react-dnd/react-dnd/issues/325
@fanties 你也可以参考这个解决方案

**Comment by fanties** [comment]
> 

这个解决不了，看来是dnd原理不支持
