### ISSUE TITLE
如何获取Drop所在的DOM节点？

### ISSUE THREAD

**Issue by bigfacewo** [hcg1023/vue3-dnd#36]
vue3-dnd: 2.0.2
vue: 3.2.37

您好，我有一个问题想请教一下。

我该如何获取drop所在的DOM节点？

```
const [collectedProps, drop] = useDrop(() => ({...}));
```
通过`:ref="drop"`传递给dom节点，在后续的方法中我想通过drop.value获取dom，但是不可行，我从文档中没能确定是否可以通过该方法获取dom。我想获取dom节点之后，通过getClientOffset的值来计算鼠标相对于drop所在节点的相对位置。通常在vue3就是通过ref来绑定获取dom的，但是这里被占用了，我也可以通过直接操作dom来实现，但是我认为该方法不好，您能提供一些建议吗？
@hcg1023

**Comment by hcg1023** [comment]
可以参考下边的示例

https://hcg1023.github.io/vue3-dnd/example/sortable/simple.html
![image](https://user-images.githubusercontent.com/47942469/187376723-5c069765-6f7b-43a5-b667-e000d6415bd5.png)
![image](https://user-images.githubusercontent.com/47942469/187376791-1df8ca1d-81cc-46d0-8447-13c80ed34d68.png)
