### ISSUE TITLE
是否支持vue2.6+，且是js的项目

### ISSUE THREAD

**Issue by 130091064** [hcg1023/vue3-dnd#37]
如题，请问 是否支持vue2.6+，且是js的项目？
项目依赖：vue2.6.14 + js

我想用这个库，报错：
1. inject() can only be used inside setup() or functional components.
2. "Invariant Violation: Expected drag drop context"

**Comment by hcg1023** [comment]
支持vue2.6，但是必须要使用 @vue/composition-api

**Comment by hcg1023** [comment]
参考文档：https://hcg1023.github.io/vue3-dnd/guide/vue2.html

**Comment by 130091064** [comment]
@vue/composition-api 这个包引入了，但我的项目是js，不是ts，
在 useDrag 这步已经报错了，都还没走到 ref 那步。

**Comment by hcg1023** [comment]
js或者ts没关系，可以看看代码怎么写的吗？
另外"Invariant Violation: Expected drag drop context"这个报错是因为没有使用DndProvider组件

**Comment by 130091064** [comment]
<a-modal
      class="common-modal"
      :maskClosable="false"
      title="添加表达式"
      :visible="true"
      :footer="null"
      width="1100px"
      :zIndex="999999"
      :destroyOnClose="true"
    >
      <DndProvider :backend="HTML5Backend">
        <a-row type="flex" class="virtual_exp">
          <a-col flex="300px" class="left">
            <a-tree showIcon>
              <a-icon slot="switcherIcon" type="down" />
              <a-tree-node v-for="system in treeData" :key="system.key">
                <span slot="title">{{ system.title }}</span>
                <a-tree-node v-for="device in system.children" :key="device.key">
                  <span slot="title">{{ device.title }}</span>
                  <a-tree-node v-for="field in device.children" :key="field.key" is-leaf>
                    <div slot="title" :ref="fieldRef" role="FIELD" :data-testid="field.key">
                      {{ field.title }}
                    </div>
                  </a-tree-node>
                </a-tree-node>
              </a-tree-node>
            </a-tree>
          </a-col>
        </a-row>
      </DndProvider>
    </a-modal>


import { useDrag, DndProvider, useDrop } from 'vue3-dnd'
import { ref } from '@vue/composition-api'
import { HTML5Backend } from 'react-dnd-html5-backend'

created() {
下面这步已经报错
   const [collect, drag] = useDrag(() => ({
      type: 'FIELD',
      item: () => ({
        name: props.name,
      }),
      end: (item, monitor) => {
        const dropResult = monitor.getDropResult()
        if (item && dropResult) {
          console.log(item)
          alert(`You dropped ${item.name} into ${dropResult.name}!`)
        }
      },
      collect: (monitor) => ({
        isDragging: monitor.isDragging(),
        handlerId: monitor.getHandlerId(),
      }),
    }))
下面这步没执行，阻塞了
    console.log(collect, drag)
    this.fieldRef = ref()

    drag(this.fieldRef)
}

**Comment by hcg1023** [comment]
需要在setup函数中调用useDrag

**Comment by 130091064** [comment]
方便加qq吗？
刚放到setup中，还是报错：
Injection "Symbol(DndContextType)" not found.
Error in data(): "Invariant Violation: Expected drag drop context"
Invariant Violation: Expected drag drop context

**Comment by hcg1023** [comment]
这个就是因为没有包DndProvider组件

**Comment by 130091064** [comment]
我有在节点中包裹，App.vue中我也试过，都不行

**Comment by hcg1023** [comment]
![image](https://user-images.githubusercontent.com/47942469/191222049-79a2ba07-fddf-4490-ad3d-6ba3e7f3d5c1.png)
微信
