### ISSUE TITLE
Dnd Indicator Mode? Can do it?

### ISSUE THREAD

**Issue by songispm** [hcg1023/vue3-dnd#38]
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/38745323/194370135-f0d0e1ae-bdb3-4df9-9677-ed1502f610cb.png">

example: [https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/examples-pages-layout--horizontal](https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/examples-pages-layout--horizontal)

**Comment by hcg1023** [comment]
Of course, it is recommended that you handle it in the hover event of the drop element

**Comment by songispm** [comment]
Can you give a demo when you have time? Also can add it to vue3-dnd docs

**Comment by hcg1023** [comment]
I added a simple example 
https://hcg1023.github.io/vue3-dnd/example/sortable/indicator.html
