### ISSUE TITLE
拖拽预览不生效

### ISSUE THREAD

**Issue by xutm** [hcg1023/vue3-dnd#39]
使用 react-dnd-touch-backend，拖拽预览不生效。

**Comment by hcg1023** [comment]
这个问题我仔细研究了一下react-dnd的现有issue，发现react-dnd的touch-backend就存在这样的问题，目前大部分人的解决方案是使用了https://github.com/LouisBrunner/dnd-multi-backend这个库，关于这个库我没有试过，之后会找时间试一下

**Comment by xutm** [comment]
> 可以提供一份出问题的示例代码吗？

https://hcg1023.github.io/vue3-dnd/example/sortable/simple.html 

这个 Demo，最外层如下写法：

```
<script setup lang="ts">
import { DndProvider } from 'vue3-dnd'
import { TouchBackend } from 'react-dnd-touch-backend'
</script>

<template>
  <DndProvider :backend="TouchBackend">
    <!-- Your Drag-and-Drop Application -->
  </DndProvider>
</template>
```

**Comment by hcg1023** [comment]
短期之内在使用touch-bakend的时候，你可以使用useDragLayer自行实现preview，如https://hcg1023.github.io/vue3-dnd/example/drag-around/custom-drag-layer.html
之后会考虑实现vue版本的https://github.com/LouisBrunner/dnd-multi-backend

**Comment by hcg1023** [comment]
我这边试着是可以的，你切换成移动设备模式的时候，有刷新页面吗？目前对于和backend的切换是没有做响应式的，必须刷新一下
