### ISSUE TITLE
Can't be drag after dragged two times

### ISSUE THREAD

**Issue by Lisuiwen** [hcg1023/vue3-dnd#43]
if i have dragged more than two times, the "draggable" on box would change to false,and then I cant drag it anymore
![E7E2710F-6252-4f8b-95CF-74BAE5B202CB](https://user-images.githubusercontent.com/32694381/217457842-ac54733e-e719-4a5c-83dc-c2cad6e66b0d.png)

**Comment by hcg1023** [comment]
Need to provide a problematic code or a minimal implementation that can reproduce the problem

**Comment by Lisuiwen** [comment]
我已经解决，问题在于box的key，我在key上加上时间戳就可以一直拖动了

**Comment by hcg1023** [comment]
👍
