### ISSUE TITLE
使用vue-tsc && vite build编译之后，页面console报错

### ISSUE THREAD

**Issue by sleiphur** [hcg1023/vue3-dnd#44]
如题，在vite中新建一个项目之后，使用DndProvider :backend="HTML5Backend"包裹了div之后，直接vite跑起来没有问题，但是在使用vue-tsc && vite build编译之后，在http-server中跑起来访问静态页面时，控制台报错：Invariant Violation: Expected drag drop context

请问这个问题有什么解决办法吗？

**Comment by hcg1023** [comment]
这个报错是因为下层的组件找不到上层的Backend,检查一下你的DndProvider是不是写在App.vue的？

**Comment by sleiphur** [comment]
感谢，按照你的方法修改后已经成功。
