### ISSUE TITLE
how to use with elment plus <el-tree>

### ISSUE THREAD

**Issue by nozuonodienobb** [hcg1023/vue3-dnd#49]
i find it not work for element plus <el-tree><slot></slot></el-tree>,

**Comment by hcg1023** [comment]
<img width="822" alt="image" src="https://github.com/hcg1023/vue3-dnd/assets/47942469/21fd17e7-ee37-4f5c-a7d3-5484a0f58c87">
The problem occurs because element-plus stops the event

**Comment by yang16** [comment]
Can you tell me how to solve it @hcg1023

**Comment by yang16** [comment]
在el-tree里面拖拽，没有走useDrag

**Comment by hcg1023** [comment]
并没有合适的解决方案，因为dnd也是监听内部元素的事件，从组件层面已经阻止了，外部是监听不到的 @yang16

**Comment by yang16** [comment]
这个dnd是和el组件某个版本不兼容吗，我这边的代码，用的el-tree，原来是可以拖拽的，现在不行了

**Comment by hcg1023** [comment]
> 这个dnd是和el组件某个版本不兼容吗，我这边的代码，用的el-tree，原来是可以拖拽的，现在不行了

具体element-plus的版本代码没有研究过，但是他内部加了stop以后就不行了

**Comment by yang16** [comment]
好的，谢谢，我在看下
