### ISSUE TITLE
拖动时的预览图能否设置样式

### ISSUE THREAD

**Issue by xf-ngc7293** [hcg1023/vue3-dnd#51]
您好，我在使用过程中有个难以处理的地方，就是拖动时生成的previewImage阻挡了鼠标与下面元素的交互事件，比如拖动过程中希望触发下面元素的mouseenter，mouseleave等事件，所以期望可以通过设置previewImage样式pointer-events: none;来达到目的。不知能否实现，或者可以有其他解决方式？谢谢

**Comment by hcg1023** [comment]
你这个需求很奇怪，你是不是想知道被拖拽元素是否进入了某个元素？或者离开了某个元素？你可以试试useDrop的hover参数

**Comment by xf-ngc7293** [comment]
> 你这个需求很奇怪，你是不是想知道被拖拽元素是否进入了某个元素？或者离开了某个元素？你可以试试useDrop的hover参数
是这样的，我有n个大区域，每个里面包含5个可拖放区域，我需要在拖动时知道鼠标是否进入、离开了相应的大区域
![image](https://github.com/hcg1023/vue3-dnd/assets/36105573/5f93f901-47ea-41d7-8c05-847d790cde77)

**Comment by hcg1023** [comment]
你的需求其实可以拆解，
离开了A区域的A1-A5,进入了B区域的B1-B5,
你需要知道，一个元素同时只可能存在于一个drop容器内，所以你可以通过一个global state，来记录元素当前所在位置，然后在每一个drop的hover中，将它改变，prevState就是离开的区域，nextState就是进入的区域

**Comment by hcg1023** [comment]
👍
