### ISSUE TITLE
Plans to support iOS?

### ISSUE THREAD

**Issue by 9mm** [hcg1023/vue3-dnd#52]
I noticed all the demo examples are broken on iPhone, even the simple examples. Is this something thats on the roadmap?

**Comment by hcg1023** [comment]
You can try the react-dnd example to see if it works on your machine
https://react-dnd.github.io/react-dnd/examples/dustbin/single-target

**Comment by 9mm** [comment]
Awesome you rock, thanks!

Your example URL works properly in:

- OSX chrome
- OSX safari

It also works in iOS you just have to hold it a very long time to drag it, but it still works perfect

**Comment by 9mm** [comment]
https://hcg1023.github.io/vue3-dnd/example/dustbin/single-target.html

on this example for vue3-dnd, the 2 issues on ios are:

- the item never follows along with the finger dragging, but the dropzone does activate
- it highlights all the text as youre trying to hold down the item to begin dragging, which then prevents the drag and drop from taking place, so maybe you need pointer-events: none or something like that?

**Comment by hcg1023** [comment]
This is related to the implementation of react-dnd-touch-backend, touch-backend implements drag and drop through touchstart, touchmove, touchend and other events

**Comment by 9mm** [comment]
Yes, it takes like 5 tries to try to “grab” it because it keeps highlighting the text. Then when it does grab it and you move thumb it doesn’t show the item being dragged Sent from my iToasterOn Jun 6, 2023, at 9:14 AM, 郝晨光 ***@***.***> wrote:﻿
So on the mobile side, you can't see the dragImage

**Comment by hcg1023** [comment]
Yes, if you need to render dragImage on mobile, maybe you can try useDragLayer
https://hcg1023.github.io/vue3-dnd/example/drag-around/custom-drag-layer.html

**Comment by 9mm** [comment]
hmm ok, ill have to have a look at that. i just wanted to make sure it was possible/supported before integrating this into my project which will be fairly complex.

im building a drag-and-drop component builder, similar to this:

https://builder.io/demo

Can you think of any reason your project wouldnt work well for this before I start on it?

**Comment by hcg1023** [comment]
https://hcg1023.github.io/vue3-dnd/en/guide/faq.htmlYou can check the common problems here, if you have experience with react-dnd, vue3-dnd will not be difficult for you
