### ISSUE TITLE
关于vue3的toRefs

### ISSUE THREAD

**Issue by Fuego-Zero** [hcg1023/vue3-dnd#60]
```
const [collect, drag] = useDrag(() => ({
  type: ItemTypes.BOX,
  item: () => ({
    name: props.name,
  }),
  end: (item, monitor) => {
    const dropResult = monitor.getDropResult<DropResult>();
    if (item && dropResult) {
      alert(`You dropped ${item.name} into ${dropResult.name}!`);
    }
  },
  collect: (monitor) => ({
    isDragging: monitor.isDragging(),
    handlerId: monitor.getHandlerId(),
  }),
}));

const { isDragging } = toRefs(collect);

const opacity = computed(() => (unref(isDragging) ? 0.4 : 1));
```
这一段代码，例子里面是从@vueuse/core导入toRefs函数，但是如果直接从vue3里面引用toRefs函数，最终结果会失去响应式并且提示"expects a reactive object but received a plain one."，但是我针对collect对象使用isRef判断，得出的又是true，很奇怪为什么

**Comment by hcg1023** [comment]
vue3的toRefs是针对reactive对象生效的，而@vueuse/core的toRefs是可以针对Ref对象以及reactive对象生效的，这里我们的collect对象是一个Ref对象，所以直接使用vue3的toRefs会错误

**Comment by Fuego-Zero** [comment]
这个就很奇怪，官方文档写的并没有说是针对reactive对象，只是说针对响应式对象……

**Comment by Fuego-Zero** [comment]
> vue3的toRefs是针对reactive对象生效的，而@vueuse/core的toRefs是可以针对Ref对象以及reactive对象生效的，这里我们的collect对象是一个Ref对象，所以直接使用vue3的toRefs会错误



> vue3的toRefs是针对reactive对象生效的，而@vueuse/core的toRefs是可以针对Ref对象以及reactive对象生效的，这里我们的collect对象是一个Ref对象，所以直接使用vue3的toRefs会错误

这个就很奇怪，官方文档写的并没有说是针对响应式对象，只是说针对响应式对象……
