### ISSUE TITLE
useDrop isOver在进入放置目标时会变化两次?

### ISSUE THREAD

**Issue by xia0ming** [hcg1023/vue3-dnd#61]
拖动元素进入放置目标(无嵌套)时, isOver会进行true -> false -> true的变化
```js
const [dropCollect, drop] = useDrop({
    accept: ['BOX'],
    collect: monitor => ({
      isOver: monitor.isOver({ shallow: true })
    })
  })

const { isOver } = toRefs(dropCollect)

watch(isOver, val => {
  console.log('val')
})

// true
// false
// true
```
拖动进入时, 会打印true -> false -> true
请教是什么原因呢

**Comment by xia0ming** [comment]
其实需求是没有成功放置的回调
放置成功后的逻辑在useDrop中drop回调内,
如果是没有成功放置(拖到到其他非目标区域松开鼠标)有办法执行回调么

**Comment by hcg1023** [comment]
> 其实需求是没有成功放置的回调 放置成功后的逻辑在useDrop中drop回调内, 如果是没有成功放置(拖到到其他非目标区域松开鼠标)有办法执行回调么

可以使用`useDrag`的`end`事件，通过`monitor.didDrop()`来判断拖拽是否被处理

**Comment by xia0ming** [comment]
查了一下, isOver的问题react-dnd也存在, 而且暂时还没有修复
https://github.com/react-dnd/react-dnd/issues/3489

**Comment by xia0ming** [comment]
> > 其实需求是没有成功放置的回调 放置成功后的逻辑在useDrop中drop回调内, 如果是没有成功放置(拖到到其他非目标区域松开鼠标)有办法执行回调么
> 
> 可以使用`useDrag`的`end`事件，通过`monitor.didDrop()`来判断拖拽是否被处理

我试试, 蟹蟹大佬回复
