### ISSUE TITLE
使用官方demo报错

### ISSUE THREAD

**Issue by AprilTong** [hcg1023/vue3-dnd#64]
![image](https://github.com/hcg1023/vue3-dnd/assets/24354441/06e63bdf-b813-488c-aa39-97a3e176396a)
[https://www.vue3-dnd.com/example/dustbin/multiple-targets.html](url)
复制粘贴使用的官方例子，报错。
相关版本使用：
vue3-dnd：2.0.4
vue：3.2.20

**Comment by hcg1023** [comment]
App.vue，使用DndProvider组件了吗，所有的例子中都没有包含App.vue的内容
https://www.vue3-dnd.com/guide/components/dnd-provider.html

**Comment by AprilTong** [comment]
> App.vue，使用DndProvider组件了吗，所有的例子中都没有包含App.vue的内容 https://www.vue3-dnd.com/guide/components/dnd-provider.html

可以了，谢谢🙏
请教一下el-menu排序+拖放怎么实现呢，el-menu下可能有el-menu-item【可以拖放到el-sub-menu下】，也有可能有el-sub-menu，其下面的el-menu-item也可拖放到el-menu下面【也可拖动排序】；el-menu下的el-menu-item和el-sub-menu也可排序。

**Comment by AprilTong** [comment]
目前用的vue-draggable-next实现，但el-sub-menu收起的时候，无法拖放至下面。了解到这个插件，但看了看文档，看起来似乎要嵌套+排序的逻辑结合到一起🤦‍♀️

**Comment by hcg1023** [comment]
> 目前用的vue-draggable-next实现，但el-sub-menu收起的时候，无法拖放至下面。了解到这个插件，但看了看文档，看起来似乎要嵌套+排序的逻辑结合到一起🤦‍♀️

我觉得你可以尝试一下，如果是drop到el-sub-menu，这种组件，那你就往它的自己的子列表内添加，如果是drop到el-menu-item，那就是排序

你的需求确实比较复杂，如果使用vue-draggable-next实现的话，也可以尝试，看看能否在el-sub-menu的drop时处理，如果不能，那最好就是使用vue3-dnd，搭配排序以及drop，hover等功能去实现

**Comment by hcg1023** [comment]
因为你使用vue3-dnd的话，你可以把el-sub-menu的 title 变为一个 drop 元素，这种情况下，不论它收起或展开，你都可以在它之上去做，不论是往内部添加，还是往平级添加，都是可以的
