### ISSUE TITLE
支持单击或双击放置目标吗？

### ISSUE THREAD

**Issue by kaivin** [hcg1023/vue3-dnd#66]
我看例子里没有这种例子，不知道如何实现通过单击或者双击将拖拽源放到指定的放置目标默认位置，例子好像只能通过拖拽放置，双击是较为常用场景，单击放置是想实现如PS工具那种，通过下拉窗口点击对应工具，会在编辑区默认位置放置一个对应工具

**Comment by hcg1023** [comment]
你说的这种场景，我理解和拖拽没有关系，你只要点击的时候把数据处理好就可以了吧？因为你是放置到一个默认位置的

**Comment by hcg1023** [comment]
我们拖拽的一般都是一个数组/或者一段数据，那你点击的时候可以将元素追加到这段数据内，即可，而不是在dnd内处理

**Comment by kaivin** [comment]
嗯，明白了，用vue-draggable习惯了，那个是直接绑定数组，这个是需要绑定数组项上，一时没转过来数据怎么处理的~多谢~！
