### ISSUE TITLE
想实现基于鼠标按下后，移动了指定的x,y距离后再进行拖拽，这个在useDrag的canDrag里获取不到实时的鼠标信息，如何实现这种效果？

### ISSUE THREAD

**Issue by kaivin** [hcg1023/vue3-dnd#67]
如何实现数据拖拽指定距离后，拖拽源才能被拖拽？

**Comment by hcg1023** [comment]
你可以使用touch-backend，然后使用enableMouseEvents，使用鼠标事件来处理拖拽，同时touch-backend就支持delay
https://www.vue3-dnd.com/guide/backend/touch.html#options%E9%80%89%E9%A1%B9

**Comment by hcg1023** [comment]
以及touchSlop属性，发出拖动之前移动的距离
