### ISSUE TITLE
useDrag 无法配置beginDrag参数

### ISSUE THREAD

**Issue by gezhigang1005** [hcg1023/vue3-dnd#68]
### 问题

> 想要实现控制某个拖拽源（Drag Sources）不可拖拽

想在在`canDrag`内部调用 `monitor.getItem()` 来判断当前是否可被拖拽。

但发现`canDrag`是在`item`函数之前执行的，所以内部的 `monitor.getItem()`函数return的一直是`null`

看了下react-dnd发现可以配置`beginDrag`参数，它是在`canDrag`之前来执行的

### 理想目标

可以配置`beginDrag`参数，让`canDrag`内部可以获取到item数据

**Comment by hcg1023** [comment]
useDrag的item参数，传入函数时，它在拖动操作开始时被触发并返回一个表示拖动操作的对象。如果返回null，则取消拖动操作，这个就是beginDrag

**Comment by hcg1023** [comment]
并且，你在useDrag的canDrag内，其实完全不需要通过getItem去获取当前元素，因为你本身就知道当前元素是什么

**Comment by gezhigang1005** [comment]
> useDrag的item参数，传入函数时，它在拖动操作开始时被触发并返回一个表示拖动操作的对象。如果返回null，则取消拖动操作，这个就是beginDrag

`canDrag `函数是在`item `函数之前执行的，所以`monitor.getItem()`一直是`null`。

**Comment by gezhigang1005** [comment]
> > useDrag的item参数，传入函数时，它在拖动操作开始时被触发并返回一个表示拖动操作的对象。如果返回null，则取消拖动操作，这个就是beginDrag
> 
> `canDrag `函数是在`item `函数之前执行的，所以`monitor.getItem()`一直是`null`。

有道理 😄

**Comment by gezhigang1005** [comment]
> 并且，你在useDrag的canDrag内，其实完全不需要通过getItem去获取当前元素，因为你本身就知道当前元素是什么

有道理，感谢 😄
