### ISSUE TITLE
想知道如何写楼层装修，例子里面没有找到，试了很久也不行。

### ISSUE THREAD

**Issue by Yer11214** [hcg1023/vue3-dnd#69]
![image](https://github.com/hcg1023/vue3-dnd/assets/39794167/949d176d-5ad1-4ff5-a4d3-54bd166bb110)
上面是图片，求作者给个思路 = = 因为获取不到 右侧的index 导致没办法插入

**Comment by hcg1023** [comment]
为什么无法获取到index？

**Comment by hcg1023** [comment]
每一个drop元素都是一个useDrop，那相对应的，你拖上去就会触发对应的hover和drop等方法，感觉就是一个普通的拖拽呢

**Comment by Yer11214** [comment]
拖拽放上去可以，但是右侧的内容每个都是一个模块，本身他们自己也可以互相排序，但是从左侧拖过来的模块放到右侧目前获取不到插入进去的index  不知道我有没有表达清楚

**Comment by hcg1023** [comment]
没太明白，这里的index是什么？左侧应该是一个对象，然后拖入到右侧列表内，此时，你拖入列表内的某个元素中，这个元素肯定有index，那这个index不就是你要的吗？
