### ISSUE TITLE
[fix]: Cannot have two HTML5 backends at the same time.

### ISSUE THREAD

**Issue by kn-msz** [hcg1023/vue3-dnd#89]
react-dnd 解决方案 https://github.com/react-dnd/react-dnd/issues/186

**Comment by hcg1023** [comment]
没有理解你的问题，能详细说说吗

**Comment by kn-msz** [comment]
我给您演示一下

**Comment by kn-msz** [comment]
> 没有理解你的问题，能详细说说吗

![应用定制中心-Google-Chrome-2024-10-24-17-32-39](https://github.com/user-attachments/assets/772fd62a-f6c7-4f7c-80c5-8ed25ec30399)

react-dnd 是这么解决的 [https://github.com/react-dnd/react-dnd/issues/186 ](url)

**Comment by hcg1023** [comment]
懂了。在vue3-dnd里，你也可以通过类似的代码解决这个问题，你可以在全局实例化backend，并传递给DndProvider

**Comment by hcg1023** [comment]
我们的DndProvider也是支持manager参数的

**Comment by kn-msz** [comment]
useDndContextInjector
useDndContextProvider
这个是吗


> 我们的DndProvider也是支持manager参数的

**Comment by hcg1023** [comment]
<img width="576" alt="image" src="https://github.com/user-attachments/assets/dc688122-fe68-44d6-8a34-cc3dfb6ae05e">
用DndProvider组件也可以，用useDndContextProvider也可以

**Comment by kn-msz** [comment]
有实例吗

> <img alt="image" width="576" src="https://private-user-images.githubusercontent.com/47942469/379714636-dc688122-fe68-44d6-8a34-cc3dfb6ae05e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NjM3NTUsIm5iZiI6MTcyOTc2MzQ1NSwicGF0aCI6Ii80Nzk0MjQ2OS8zNzk3MTQ2MzYtZGM2ODgxMjItZmU2OC00NGQ2LThhMzQtY2MzZGZiNmFlMDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA5NTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZDBhMzMxYzJjZTZkNDhlZjI2Njg1MGMzMDA5OThiYTIxMjk5ZWNiNjZiMzM1OGJkMGQyNTZiMzBjOTg0YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4qNTy6B4Sf3XuoavWF3yFKmCWmUqGW6-AF4zVcz2X7M"> 用DndProvider组件也可以，用useDndContextProvider也可以

**Comment by hcg1023** [comment]
还有一种方法更加简单，你可以传递一个context对象给DndProvider组件

**Comment by hcg1023** [comment]
或者将你的DndProvider提取到App.vue，均可以解决你的问题

**Comment by kn-msz** [comment]
> context

对象内容是什么

**Comment by hcg1023** [comment]
任意，空对象也可以，最好是在你的两个页面下，分别唯一，即可

**Comment by hcg1023** [comment]
https://github.com/react-dnd/react-dnd/issues/186#issuecomment-978206387
也可以参考这条，将context传递为上层element对象

**Comment by hcg1023** [comment]
确保在你的两个页面下，这两个context不相同就可以了

**Comment by kn-msz** [comment]
`>` [react-dnd/react-dnd#186 (comment)](https://github.com/react-dnd/react-dnd/issues/186#issuecomment-978206387) 也可以参考该链接，将context传递为上层element对象
```

参考代码

import {  defineComponent, ref, onMounted, watch } from 'vue'
import { HTML5Backend } from 'react-dnd-html5-backend'
import { DndProvider } from 'vue3-dnd'


const DndWrapper = defineComponent({
    props: {
        id: {
            type: String,
            required: true,
        },
    },
    setup(props, {slots}) {
        const context = ref<HTMLElement | null>(null);

        onMounted(() => {
            context.value = document.getElementById(props.id);
        });

        watch(() => props.id, (newId) => {
            context.value = document.getElementById(newId);
        });

        return () => (
            context.value ? (
                <DndProvider backend={ HTML5Backend } options={ {rootElement: context.value} }>
                    { slots?.default?.() }
                </DndProvider>
            ) : null
        );
    },
})
```

可以了 多谢老板
