### ISSUE TITLE
是否能解决直接绑定ui库的组件

### ISSUE THREAD

**Issue by ashuicoder** [hcg1023/vue3-dnd#92]
我看到[vue-draggable-plus](https://vue-draggable-plus.pages.dev/guide/)里有这样一段描述。
<img width="793" alt="image" src="https://github.com/user-attachments/assets/886f0fb1-cf35-4815-bb49-c76a3a9101c1">
但是dnd直接绑定没有跟元素的 组件是会直接报错的，有没有办法手动制定到dom元素
<img width="568" alt="image" src="https://github.com/user-attachments/assets/4e0ab037-47e2-4321-827f-62154f4e0619">

**Comment by hcg1023** [comment]
vue-draggable-plus是Sortablejs的包装层，它的内部会自动获取列表和列表元素处理排序的拖拽，所以它只需要获取到最外层的list节点即可，但是对dnd而言，所有的节点均需手动绑定，以便于提供更灵活的拖拽效果

**Comment by ashuicoder** [comment]
> vue-draggable-plus是Sortablejs的包装层，它的内部会自动获取列表和列表元素处理排序的拖拽，所以它只需要获取到最外层的list节点即可，但是对dnd而言，所有的节点均需手动绑定，以便于提供更灵活的拖拽效果
那请问有手动绑定的示例吗

**Comment by hcg1023** [comment]
使用dnd，如果需要获取组件内的节点，你需要使用querySelector来手动获取

<img width="1077" alt="image" src="https://github.com/user-attachments/assets/0eb41db8-2a26-4093-8519-4a601ebcef00">

**Comment by ashuicoder** [comment]
> 使用dnd，如果需要获取组件内的节点，你需要使用querySelector来手动获取
> 
> <img alt="image" width="1077" src="https://private-user-images.githubusercontent.com/47942469/391234220-0eb41db8-2a26-4093-8519-4a601ebcef00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzA5ODAsIm5iZiI6MTczMjk3MDY4MCwicGF0aCI6Ii80Nzk0MjQ2OS8zOTEyMzQyMjAtMGViNDFkYjgtMmEyNi00MDkzLTg1MTktNGE2MDFlYmNlZjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDEyNDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YzcxNzQxMTA5N2E4NmZlYzBkMDJhOGIwZGY3MzY0YWRjZjEyOTM5MTIyMzA1NDJkNmI4OWYzNzU4MTNiZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ufGAPCn2uIgJFLbqpyuPVcPkw1Edtv63GVzMXVc7F4w">

已解决，直接使用dropBind(el.$el)就能绑定组件的元素了，当然了，如果存在的话
```ts
function setDrop(el: HTMLElement | Record<string, any> | null) {
  if (!el) return
  if (!node.canDrop) {
    dropBind(null)
    return
  }
  if (el instanceof window.HTMLElement) {
    dropBind(el)
    return
  }
  dropBind(el.$el)
}

```
