### ISSUE TITLE
accept问题

### ISSUE THREAD

**Issue by ashuicoder** [hcg1023/vue3-dnd#93]
当使用嵌套拖拽的时候，useDrop的accept属性不是写死的时候会有问题，动态计算的时候子元素的accept失效，drop方法永远都会触发到最外层的使用了useDrop的元素，即使子元素的drop直接return了还是会导致最外层的元素drop触发。但是accept直接写死drop事件就没问题。accept直接动态计算的是都失效的，还是能拖拽。
仓库代码[示例](https://github.com/ashuicoder/lowcode-engine)

**Comment by hcg1023** [comment]
这个问题是否还存在呢？

**Comment by ashuicoder** [comment]
> 这个问题是否还存在呢？

存在的

**Comment by hcg1023** [comment]
你的仓库目前404了，我需要一个示例

**Comment by ashuicoder** [comment]
> 你的仓库目前404了，我需要一个示例

https://github.com/ashuicoder/lowcode-engine

**Comment by hcg1023** [comment]
能再详细介绍一下我该怎么操作复现吗

**Comment by ashuicoder** [comment]
![image](https://github.com/user-attachments/assets/468c8c2c-ba85-4c12-8286-a884c881af78)
你可以先拖一个“图片””到中间，再拖一个其他元素到图片上就会触发了。其实图片的accept的是空数组的，但是还是在最外层触发了

**Comment by hcg1023** [comment]
你的意思是，如果内层的drop阻止掉了，那在上层组件上也不应该触发？

**Comment by ashuicoder** [comment]
> 你的意思是，如果内层的drop阻止掉了，那在上层组件上也不应该触发？

那肯定嘛，不然我做这个嵌套拖拽就没意义了，这里应该是有两个问题的： 1是accept为什么动态计算的时候就失效了，按道理来说我组件渲染的时候accept已经计算好了，我能不能拖到这个元素上，如果type和aceept没有关系应该是直接禁止拖拽的。2是假如accept通过了，到drop事件里了，我直接return了，肯定要阻止自己和祖先的事件啊，不然我是精准拖拽到这个元素的，导致在其祖先元素触发了，这里有问题的。

**Comment by hcg1023** [comment]
是这样的，img你指定了accept为空，所以往img拖拽其它组件时，img的drop就不会被触发，它会直接在上层支持的组件处触发

**Comment by hcg1023** [comment]
按你的描述，我认为你的所有组件的accept应该均为ALL，然后在drop中通过你的方法进行判断，如果不允许放置，则在drop中return {stop: true},如果允许放置，则return {done: true};这样你可以在上层的drop中拿到DropResult，同时跳过stop的内容

**Comment by hcg1023** [comment]
嵌套的不允许放置，就会在上层触发，而不是直接将你的内容丢弃掉

**Comment by hcg1023** [comment]
<img width="708" alt="image" src="https://github.com/user-attachments/assets/fac71220-8527-467f-beef-c38dff5b0f45" />
就是这个意思，我试了一下，这样就可以了

**Comment by ashuicoder** [comment]
> <img alt="image" width="708" src="https://private-user-images.githubusercontent.com/47942469/395938661-fac71220-8527-467f-beef-c38dff5b0f45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTYzMDMsIm5iZiI6MTczNDMxNjAwMywicGF0aCI6Ii80Nzk0MjQ2OS8zOTU5Mzg2NjEtZmFjNzEyMjAtODUyNy00NjdmLWJlZWYtYzM4ZGZmNWIwZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAyMjY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZDYwMDNmNWYyZGY0NDc4ZTU2Nzc1YWU3MmY4ZjhmOTBiNDMyMzhhYjNmNjI4YzBlMWJiZmU0OTZlMDgwZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n-c7aoJXZMz5ZEBc1VBE-2oqYFfo8NK852mfYm2wOxo"> 就是这个意思，我试了一下，这样就可以了

这个方法其实相当于所有的元素的accept都是一样的了，我试过了可以的，但是accept不一样的时候就不行了

**Comment by ashuicoder** [comment]
> > <img alt="image" width="708" src="https://private-user-images.githubusercontent.com/47942469/395938661-fac71220-8527-467f-beef-c38dff5b0f45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTYzMDMsIm5iZiI6MTczNDMxNjAwMywicGF0aCI6Ii80Nzk0MjQ2OS8zOTU5Mzg2NjEtZmFjNzEyMjAtODUyNy00NjdmLWJlZWYtYzM4ZGZmNWIwZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAyMjY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZDYwMDNmNWYyZGY0NDc4ZTU2Nzc1YWU3MmY4ZjhmOTBiNDMyMzhhYjNmNjI4YzBlMWJiZmU0OTZlMDgwZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n-c7aoJXZMz5ZEBc1VBE-2oqYFfo8NK852mfYm2wOxo"> 就是这个意思，我试了一下，这样就可以了
> 
> 这个方法其实相当于所有的元素的accept都是一样的了，我试过了可以的，但是accept不一样的时候就不行了

麻烦大佬看看是react-dnd的问题还是vue-dnd的问题

**Comment by hcg1023** [comment]
对，所有的accept都是一样，这个我们不认为是问题，react-dnd设计如此

**Comment by hcg1023** [comment]
我可以详细介绍一下：
1. accept命中，会执行drop
2. accept不命中，不执行drop
3. 如果嵌套的drop组件，内层不命中，外层命中，就会走外层的drop，你可以理解为事件冒泡

**Comment by ashuicoder** [comment]
> 我可以详细介绍一下：
> 
> 1. accept命中，会执行drop
> 2. accept不命中，不执行drop
> 3. 如果嵌套的drop组件，内层不命中，外层命中，就会走外层的drop，你可以理解为事件冒泡

那这种确实没办法了，只能用drop方法来处理了。没办法阻止冒泡吗？

**Comment by hcg1023** [comment]
这个确实没有办法，大部分场景下，还是需要命中外层drop的，像你这种不命中直接丢弃的场景确实比较特殊，我反而认为命中外层，对于用户而言更加友好，比如你刚刚的示例中，我想在画布中添加一个文本，不小心放到了img上，你就丢弃掉了，我就得重新拖一次
